### ISSUE TITLE
output includes deps

### ISSUE THREAD

**Issue by mayank99** [iTwin/synchronization-report-react#48]
The output of this package (compiled `index.js`) includes a bunch of dependencies which bloat up the bundle size. I noticed `react-dom`, `tippy.js` and `classnames` were being included; there are likely more. This behavior is wrong because the application consuming this package should be responsible for bundling those dependencies, otherwise it could result in multiple copies of each package being shipped to the user.

All dependency packages can be externalized here to make the output smaller:
https://github.com/iTwin/synchronization-report-react/blob/2977384ec7164ff0324dc242d232425734ddc4cb/vite.config.js#L21

**Comment by mayank99** [comment]
@Guillar1 I can create a PR for this if you'd like.

**Comment by Guillar1** [comment]
> @Guillar1 I can create a PR for this if you'd like.

Hey @mayank99, thanks for this. If it isn't too much to ask, yeah go for it.

**Comment by mayank99** [comment]
Done (#52). Sorry about the delay 😅
